version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    groups:
      frontend:
        patterns: ['*']
    open-pull-requests-limit: 5

  - package-ecosystem: cargo
    directory: '/src-tauri'
    schedule:
      interval: weekly
    groups:
      rust:
        patterns: ['*']
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
